import { escapeHtml as esc, formatDate } from './content.mjs';

const dateLabel = (label, date) => date ? `<p class="content-date">${label}: <time datetime="${esc(date)}">${esc(formatDate(date))}</time></p>` : '';
export const imageMarkup = record => record.image ? `<figure class="content-figure"><img src="${esc(record.image)}" alt="${esc(record.image_alt)}" width="${record.image_width}" height="${record.image_height}" loading="lazy" decoding="async"><figcaption>${esc(record.image_credit)}</figcaption></figure>` : '';
export function contentCard(record, experience = false) {
  return `<article class="content-card"${experience ? ` data-experience data-title="${esc(record.title + ' ' + record.excerpt)}" data-initiative="${esc(record.initiative)}" data-territory="${esc(record.territory)}"` : ''}>${imageMarkup(record)}<div class="content-card-body"><p class="section-tag">${esc(experience ? record.initiative : record.category)}</p><h2><a href="${esc(record.url)}">${esc(record.title)}</a></h2><p>${esc(record.excerpt)}</p>${experience ? `<p class="content-territory">${esc(record.territory)}</p>` : dateLabel('Publicación', record.date)}<a class="content-read" href="${esc(record.url)}">${experience ? 'Leer experiencia' : 'Leer noticia'} <span aria-hidden="true">→</span><span class="sr-only">: ${esc(record.title)}</span></a></div></article>`;
}

export function createPageRenderer(index) {
  const nav = index.match(/<nav\b[^>]*id="mainNav"[\s\S]*?<\/nav>/)?.[0];
  const footer = index.match(/<footer\b[^>]*>[\s\S]*?<\/footer>/)?.[0];
  if (!nav || !footer) throw new Error('index.html debe contener nav#mainNav y footer compartidos');
  const normalize = html => html.replace(/href="#([^"\s]+)"/g, 'href="/#$1"').replace(/(?:src|href)="(assets\/[^"\s]+)"/g, (match, resource) => match.replace(resource, `/${resource}`));
  const css = Array.from(index.matchAll(/<link\b[^>]*href="(?:\/)?assets\/css\/[^"\s]+"[^>]*>/g)).map(match => normalize(match[0])).join('\n');
  const fonts = Array.from(index.matchAll(/<link\b[^>]*href="https:\/\/fonts\.[^"\s]+"[^>]*>/g)).map(match => match[0]).join('\n');
  return ({ title, description, url, content, script = '', noindex = false }) => `<!DOCTYPE html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | AFNEMO</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://afnemo.co${esc(url)}"><meta property="og:title" content="${esc(title)} | AFNEMO"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="https://afnemo.co${esc(url)}">${noindex ? '<meta name="robots" content="noindex">' : ''}${fonts}${css}<link rel="stylesheet" href="/assets/css/content.css"></head>
<body class="content-page"><a class="skip-link" href="#main-content">Saltar al contenido</a>${normalize(nav)}<main id="main-content" tabindex="-1" class="content-main">${content}</main>${normalize(footer)}<script src="/assets/js/nav.js" defer></script>${script ? `<script src="${script}" defer></script>` : ''}</body></html>`;
}

export function newsList(records) {
  return `<header class="content-heading"><a class="content-back" href="/">← Inicio</a><p class="section-tag">Noticias y eventos</p><h1>Noticias de AFNEMO</h1><p>Actualidad y relatos publicados por la asociación.</p></header>${records.length ? `<div class="content-grid">${records.map(record => contentCard(record)).join('')}</div>` : '<div class="content-notice"><h2>Aún no hay noticias publicadas</h2><p>Este espacio reunirá las próximas publicaciones de AFNEMO.</p><a href="/experiencias/">Explorar experiencias documentadas →</a></div>'}`;
}

export function newsDetail(record) {
  return `<article class="content-article"><header class="content-heading"><a class="content-back" href="/noticias/">← Todas las noticias</a><p class="section-tag">${esc(record.category)}</p><h1>${esc(record.title)}</h1><p class="content-lead">${esc(record.excerpt)}</p>${dateLabel('Publicación', record.date)}${dateLabel('Fecha del evento', record.event_date)}${dateLabel('Actualización', record.updated_at)}</header>${imageMarkup(record)}<div class="prose">${record.html}</div>${record.source ? `<aside class="content-sources"><h2>Fuente documental</h2><p>${esc(record.source)}</p>${dateLabel('Fecha de la fuente', record.source_date)}</aside>` : ''}<a class="content-back" href="/noticias/">← Volver a noticias</a></article>`;
}

export function experiencesList(records) {
  const options = field => [...new Set(records.map(record => record[field]))].sort((a, b) => a.localeCompare(b, 'es')).map(value => `<option value="${esc(value)}">${esc(value)}</option>`).join('');
  return `<header class="content-heading"><a class="content-back" href="/">← Inicio</a><p class="section-tag">Memoria y territorio</p><h1>Experiencias de AFNEMO</h1><p>Relatos documentados de las iniciativas y los territorios que hacen parte de nuestra memoria.</p><p class="content-notice">Las fichas distinguen los antecedentes documentados de la actividad actual. La revisión documental no confirma su operación vigente.</p><a href="/#mapa-institucional">Consultar el mapa externo de emprendimientos →</a></header>${records.length ? `<form class="experience-filters" id="experience-filters" role="search" hidden><div><label for="experience-query">Buscar en los relatos</label><input type="search" id="experience-query" name="q" placeholder="Título o resumen"></div><div><label for="experience-initiative">Iniciativa</label><select id="experience-initiative" name="initiative"><option value="">Todas las iniciativas</option>${options('initiative')}</select></div><div><label for="experience-territory">Territorio</label><select id="experience-territory" name="territory"><option value="">Todos los territorios</option>${options('territory')}</select></div><button type="reset" class="content-reset">Limpiar filtros</button></form><p id="experience-count" class="content-count" role="status">${records.length} experiencias</p><div class="content-grid">${records.map(record => contentCard(record, true)).join('')}</div><p id="experience-empty" class="content-notice" hidden>No hay experiencias con estos filtros. Prueba otro término o limpia los filtros.</p><noscript><p class="content-notice">Se muestran todas las experiencias. Activa JavaScript para usar los filtros.</p></noscript>` : '<p class="content-notice">Las experiencias documentadas estarán disponibles después de su revisión editorial.</p>'}`;
}

export function experienceDetail(record) {
  const precisions = { none: 'Sin ubicación pública', city: 'Ciudad', locality: 'Localidad', region: 'Región' };
  return `<article class="content-article"><header class="content-heading"><a class="content-back" href="/experiencias/">← Todas las experiencias</a><p class="section-tag">${esc(record.initiative)}</p><h1>${esc(record.title)}</h1><p class="content-lead">${esc(record.excerpt)}</p><dl class="content-facts"><div><dt>Territorio documentado</dt><dd>${esc(record.territory)}</dd></div><div><dt>Precisión pública</dt><dd>${precisions[record.public_precision]}</dd></div></dl>${dateLabel('Fecha documentada', record.event_date)}</header><p class="content-notice">Experiencia histórica según las fuentes citadas. Su operación actual no está confirmada por esta ficha.</p>${imageMarkup(record)}<div class="prose">${record.html}</div>${record.milestones.length ? `<section class="content-sources"><h2>Hitos documentados</h2><ul>${record.milestones.map(item => `<li><time datetime="${esc(item.date)}">${esc(formatDate(item.date))}</time>: ${esc(item.label)}</li>`).join('')}</ul></section>` : ''}${record.materials.length ? `<section class="content-sources"><h2>Materiales relacionados</h2><ul>${record.materials.map(item => `<li><a href="${esc(item.url)}" rel="noopener noreferrer">${esc(item.label)}</a>${item.credit ? ` — ${esc(item.credit)}` : ''}</li>`).join('')}</ul></section>` : ''}<aside class="content-sources"><h2>Fuente y revisión</h2><p>${esc(record.source)}</p>${dateLabel('Revisión documental', record.reviewed_at)}<p>Las ubicaciones se expresan con la precisión indicada; no representan una dirección de atención.</p></aside><a class="content-back" href="/experiencias/">← Volver a experiencias</a></article>`;
}
